[build]
builder = "nixpacks"
buildCommand = "cd charges-fields-lab-app && npm install && npm run build"

[deploy]
startCommand = "cd charges-fields-lab-app && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 