[build]
builder = "nixpacks"
nixPkgs = ["nodejs_18"]
buildCommand = "cd charges-fields-lab-app && npm clean-install && chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "cd charges-fields-lab-app && npx serve dist -l 3333 --single --no-clipboard --cors"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10