[build]
builder = "nixpacks"
buildCommand = "cd charges-fields-lab-app && npm install && npm run build"

[deploy]
startCommand = "npx serve -s charges-fields-lab-app/dist -l 3333"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 