[build]
builder = "nixpacks"
# nixPkgs, buildCommand are now defined in nixpacks.toml

[deploy]
# startCommand is now defined in nixpacks.toml
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10